### ISSUE TITLE
Pirate fleets spawn with different side than pirate faction (5) 

### ISSUE THREAD

**Issue by camylarde** [tsnrp/Command-Systems-XML-Files#3]
Small medium and large Skull pirate fleets spawn with different side than the rest of Pirate faction (side 5) single ships.

**Comment by astrolamb-gaming** [comment]
Confirmed, this is caused by the pirate fleets not being assigned a side at spawn.

**Comment by astrolamb-gaming** [comment]
Shouldn't be too hard to fix, the pirate fleets just need the sideValue="SideValue" bit added to the spawn commands

**Comment by XavierWise** [comment]
fixed
